2021-03-04 19:16:23,095 :: client.py:59 :: INFO :: Done with config initialization
2021-03-04 19:16:23,100 :: client.py:388 :: INFO :: Started server successfully at address: ('127.0.1.1', 24317)
2021-03-04 19:16:31,047 :: client.py:340 :: INFO :: Sent data: b'\x00\x00\x04' to ('127.0.1.1', 7672)
2021-03-04 19:16:31,469 :: client.py:348 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:16:31,515 :: client.py:340 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:31,608 :: client.py:348 :: INFO :: Sent ACK for seq: 1
2021-03-04 19:16:31,656 :: client.py:340 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:33,060 :: client.py:348 :: INFO :: Sent ACK for seq: 2
2021-03-04 19:16:33,076 :: client.py:340 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:33,216 :: client.py:348 :: INFO :: Sent ACK for seq: 3
2021-03-04 19:16:33,247 :: client.py:340 :: INFO :: Sent data: b'\x03\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:34,748 :: client.py:348 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:16:34,780 :: client.py:340 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:34,903 :: client.py:348 :: INFO :: Sent ACK for seq: 1
2021-03-04 19:16:34,935 :: client.py:340 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:36,283 :: client.py:348 :: INFO :: Sent ACK for seq: 2
2021-03-04 19:16:36,284 :: client.py:340 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:36,439 :: client.py:348 :: INFO :: Sent ACK for seq: 3
2021-03-04 19:16:36,470 :: client.py:340 :: INFO :: Sent data: b'\x03\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:38,155 :: client.py:348 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:16:38,186 :: client.py:340 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:38,328 :: client.py:348 :: INFO :: Sent ACK for seq: 1
2021-03-04 19:16:38,342 :: client.py:340 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:39,702 :: client.py:348 :: INFO :: Sent ACK for seq: 2
2021-03-04 19:16:39,750 :: client.py:340 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:39,762 :: /mnt/d/SocketProg/PyTorrent/utils.py:42 :: INFO :: Verify hash of file configs/clients/2/downloads/4.txt
2021-03-04 19:16:39,779 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/4.txt
2021-03-04 19:16:39,963 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/4.txt
2021-03-04 19:16:40,031 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/4.txt
2021-03-04 19:16:40,213 :: client.py:123 :: INFO :: File hash verified: configs/clients/2/downloads/4.txt
2021-03-04 19:16:40,228 :: client.py:308 :: INFO :: Request for 4 from 7672 completed successfully.
2021-03-04 19:18:57,639 :: client.py:340 :: INFO :: Sent data: b'\x00\x00\x02' to ('127.0.1.1', 7672)
2021-03-04 19:18:57,733 :: client.py:348 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:18:57,780 :: client.py:340 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7672)
2021-03-04 19:18:57,796 :: client.py:219 :: INFO :: Connection complete after receiving file from ('127.0.1.1', 7672)
2021-03-04 19:18:57,796 :: client.py:118 :: INFO :: Empty file detected: configs/clients/2/downloads/2.txt
2021-03-04 19:18:57,842 :: client.py:308 :: INFO :: Request for 2 from 7672 completed successfully.
2021-03-04 19:19:49,328 :: client.py:340 :: INFO :: Sent data: b'\x00\x00\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:49,686 :: client.py:348 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:19:49,733 :: client.py:340 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:49,826 :: client.py:348 :: INFO :: Sent ACK for seq: 1
2021-03-04 19:19:49,874 :: client.py:340 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:51,449 :: client.py:348 :: INFO :: Sent ACK for seq: 2
2021-03-04 19:19:51,497 :: client.py:340 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:51,608 :: client.py:348 :: INFO :: Sent ACK for seq: 3
2021-03-04 19:19:51,655 :: client.py:340 :: INFO :: Sent data: b'\x03\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:53,217 :: client.py:348 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:19:53,264 :: client.py:340 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:53,404 :: client.py:348 :: INFO :: Sent ACK for seq: 1
2021-03-04 19:19:53,404 :: client.py:340 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:54,998 :: client.py:348 :: INFO :: Sent ACK for seq: 2
2021-03-04 19:19:55,045 :: client.py:340 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:55,170 :: client.py:348 :: INFO :: Sent ACK for seq: 3
2021-03-04 19:19:55,218 :: client.py:340 :: INFO :: Sent data: b'\x03\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:56,686 :: client.py:348 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:19:56,718 :: client.py:340 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:56,937 :: client.py:348 :: INFO :: Sent ACK for seq: 1
2021-03-04 19:19:56,984 :: client.py:340 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:58,746 :: client.py:348 :: INFO :: Sent ACK for seq: 2
2021-03-04 19:19:58,793 :: client.py:340 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:58,825 :: /mnt/d/SocketProg/PyTorrent/utils.py:42 :: INFO :: Verify hash of file configs/clients/2/downloads/1.txt
2021-03-04 19:19:58,840 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/1.txt
2021-03-04 19:19:59,292 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/1.txt
2021-03-04 19:19:59,575 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/1.txt
2021-03-04 19:19:59,906 :: client.py:123 :: INFO :: File hash verified: configs/clients/2/downloads/1.txt
2021-03-04 19:19:59,952 :: client.py:308 :: INFO :: Request for 1 from 7951 completed successfully.
2021-03-04 19:21:59,955 :: client.py:59 :: INFO :: Done with config initialization
2021-03-04 19:21:59,960 :: client.py:391 :: INFO :: Started server successfully at address: ('127.0.1.1', 24317)
2021-03-04 19:23:07,124 :: client.py:343 :: INFO :: Sent data: b'\x00\x00\x04' to ('127.0.1.1', 7672)
2021-03-04 19:23:07,482 :: client.py:351 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:23:07,528 :: client.py:343 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:07,621 :: client.py:351 :: INFO :: Sent ACK for seq: 1
2021-03-04 19:23:07,669 :: client.py:343 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:08,280 :: client.py:423 :: INFO :: New connection request from ('127.0.0.1', 57100) for file 0
2021-03-04 19:23:08,372 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/0.txt
2021-03-04 19:23:08,750 :: client.py:552 :: INFO :: Sent data with seq 0
2021-03-04 19:23:08,875 :: client.py:552 :: INFO :: Sent data with seq 1
2021-03-04 19:23:09,046 :: client.py:351 :: INFO :: Sent ACK for seq: 2
2021-03-04 19:23:09,047 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 0
2021-03-04 19:23:09,108 :: client.py:343 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:09,125 :: client.py:575 :: INFO :: deleting 0
2021-03-04 19:23:09,218 :: client.py:351 :: INFO :: Sent ACK for seq: 3
2021-03-04 19:23:09,249 :: client.py:343 :: INFO :: Sent data: b'\x03\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:09,357 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 1
2021-03-04 19:23:09,371 :: client.py:575 :: INFO :: deleting 1
2021-03-04 19:23:10,469 :: client.py:625 :: WARNING :: Resend called for ('127.0.0.1', 57100) as no ack received. Retry count: 10
2021-03-04 19:23:10,531 :: client.py:552 :: INFO :: Sent data with seq 2
2021-03-04 19:23:10,562 :: client.py:351 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:23:10,625 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 2
2021-03-04 19:23:10,625 :: client.py:343 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:10,703 :: client.py:552 :: INFO :: Sent data with seq 3
2021-03-04 19:23:10,703 :: client.py:351 :: INFO :: Sent ACK for seq: 1
2021-03-04 19:23:10,811 :: client.py:343 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:10,920 :: client.py:575 :: INFO :: deleting 2
2021-03-04 19:23:10,966 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 3
2021-03-04 19:23:10,982 :: client.py:575 :: INFO :: deleting 3
2021-03-04 19:23:12,046 :: client.py:351 :: INFO :: Sent ACK for seq: 2
2021-03-04 19:23:12,062 :: client.py:625 :: WARNING :: Resend called for ('127.0.0.1', 57100) as no ack received. Retry count: 10
2021-03-04 19:23:12,093 :: client.py:343 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:12,125 :: client.py:552 :: INFO :: Sent data with seq 0
2021-03-04 19:23:12,170 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 0
2021-03-04 19:23:12,171 :: client.py:351 :: INFO :: Sent ACK for seq: 3
2021-03-04 19:23:12,185 :: client.py:343 :: INFO :: Sent data: b'\x03\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:12,265 :: client.py:552 :: INFO :: Sent data with seq 1
2021-03-04 19:23:12,437 :: client.py:575 :: INFO :: deleting 0
2021-03-04 19:23:12,532 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 1
2021-03-04 19:23:12,548 :: client.py:575 :: INFO :: deleting 1
2021-03-04 19:23:13,638 :: client.py:351 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:23:13,671 :: client.py:343 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:13,639 :: client.py:625 :: WARNING :: Resend called for ('127.0.0.1', 57100) as no ack received. Retry count: 10
2021-03-04 19:23:13,733 :: client.py:552 :: INFO :: Sent data with seq 2
2021-03-04 19:23:13,811 :: client.py:351 :: INFO :: Sent ACK for seq: 1
2021-03-04 19:23:13,826 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 2
2021-03-04 19:23:13,858 :: client.py:343 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:13,906 :: client.py:552 :: INFO :: Sent data with seq 3
2021-03-04 19:23:14,108 :: client.py:575 :: INFO :: deleting 2
2021-03-04 19:23:14,233 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 3
2021-03-04 19:23:14,233 :: client.py:575 :: INFO :: deleting 3
2021-03-04 19:23:15,273 :: client.py:625 :: WARNING :: Resend called for ('127.0.0.1', 57100) as no ack received. Retry count: 10
2021-03-04 19:23:15,273 :: client.py:351 :: INFO :: Sent ACK for seq: 2
2021-03-04 19:23:15,304 :: client.py:552 :: INFO :: Sent data with seq 0
2021-03-04 19:23:15,304 :: client.py:343 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:15,310 :: /mnt/d/SocketProg/PyTorrent/utils.py:42 :: INFO :: Verify hash of file configs/clients/2/downloads/4.txt
2021-03-04 19:23:15,311 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/4.txt
2021-03-04 19:23:15,326 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 0
2021-03-04 19:23:15,375 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/4.txt
2021-03-04 19:23:15,376 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/4.txt
2021-03-04 19:23:15,395 :: client.py:123 :: INFO :: File hash verified: configs/clients/2/downloads/4.txt
2021-03-04 19:23:15,406 :: client.py:311 :: INFO :: Request for 4 from 7672 completed successfully.
2021-03-04 19:23:15,406 :: client.py:552 :: INFO :: Sent data with seq 1
2021-03-04 19:23:15,605 :: client.py:575 :: INFO :: deleting 0
2021-03-04 19:23:15,657 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 1
2021-03-04 19:23:15,673 :: client.py:575 :: INFO :: deleting 1
2021-03-04 19:23:16,719 :: client.py:625 :: WARNING :: Resend called for ('127.0.0.1', 57100) as no ack received. Retry count: 10
2021-03-04 19:23:16,766 :: client.py:552 :: INFO :: Sent data with seq 2
2021-03-04 19:23:16,829 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 2
2021-03-04 19:23:16,909 :: client.py:575 :: INFO :: deleting 2
